### ISSUE TITLE
Up regather threshold to 8

### ISSUE THREAD

**Issue by cblanc** [cblanc/sws_gathers#40]

**Comment by Aircool** [comment]
It may be in the best interest in the long term to keep the threshold at 6 votes, but make sure that all the players remain in the gather. Provide some sort of audio queue and give them maybe 1 or 2 minutes to confirm that they are there. Otherwise they will be removed. 

Then on top of this you would need some sort of system to remove AFK people, but vote-kicking is probably not the answer due to the potential to abuse that functionality, for example for people to remove players they don't like, or just plain trolling. Perhaps the requirement that you confirm your presence at the start of the gather similar to my proposed idea of confirming your presence when re-gathering. 

I suggest such structures because realistically we don't want to punish people because they aren't there when they don't need to be. So automatically removing them or having an abuseable vote-kicking system isn't necessarily fair. But having an understood system like the one proposed will balance this desire to protect people who aren't there with the necessity to protect players from AFKs. Essentially you need to confirm your presence before voting... and if you don't then the players who are there aren't screwed over after voting and picking teams to find an AFK. And if you are afk during that time, then that is tough... but it saves everyone else time.

**Comment by Aircool** [comment]
Also an unmuteable, but non-intrusive queue whenever a gather starts, and whenever a re-gather commences to notify users that they need to confirm their presence... This is for when they are at their computers but don't want the obnoxious gather music.

**Comment by cblanc** [comment]
Simple and I were discussing doing something similar - will need to work on the finer details soon

For the time being, I've been asked to up the limit to 8 for the meantime. The list of todos is growing faster than I can manage /-:
