### ISSUE TITLE
Profile Pictures dont update

### ISSUE THREAD

**Issue by Salads** [cblanc/sws_gathers#89]
Profile Pictures dont update when you change them on ensl.org and chat in the gather app.

**Comment by Salads** [comment]
just very slow i guess

**Comment by cblanc** [comment]
Thing is it depends.

Each message stores a url to an avatar. Every time you update an image it will be saved as `http://<image_host>/<your_user_id>.<image_type>`

If the image type is the same, eventually your browser should refresh the image and it should change everywhere. 

Unfortunately, if the new image_types does not match the old one, switching to a different format will mean your previous messages won't be updated. This is probably something to be fixed on ensl.org because the rescaling/cropping should also settle on the same image type for all avatars
